# Generated by Django 4.1.3 on 2022-11-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_transactions', '0002_alter_usertransactions_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertransactions',
            name='date',
            field=models.DateField(),
        ),
    ]
