version: "3.6"

services:
  db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file: ./.db.env
    ports:
      - '5432:5432'
#    network_mode: "host"

  web:
    build: .
    volumes:
      - .:/usr/src/cost_accounting_manager
    ports:
      - '8000:8000'
    env_file: ./.env
    depends_on:
      - db
#    network_mode: "host"

  redis:
    image: redis:alpine
#    network_mode: "host"

#  celery:
#    restart: always
#    build:
#      context: .
#    entrypoint: celery -A support worker -l info
#    volumes:
#      - .:/usr/src/support
#    env_file: ./.env
#    depends_on:
#      - db
#      - redis
#      - web
#    network_mode: "host"

#celery-beat:
#  build: ./project
#  command: celery -A core beat -l info
#  volumes:
#    - ./project/:/usr/src/app/
#  depends_on:
#      - db
#      - redis
#      - web
volumes:
  data: