version: "3.6"

services:
  db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file: ./.db.env
    ports:
      - '5432:5432'

  web:
    build: .
    volumes:
      - .:/usr/src/cost_accounting_manager
    ports:
      - '8000:8000'
    env_file: ./.env
    depends_on:
      - db

  redis:
    image: redis:alpine

  celery:
    restart: always
    build:
      context: .
    entrypoint: celery -A cost_accounting_manager worker -l info
    volumes:
      - .:/usr/src/cost_accounting_manager
#    env_file: ./.email.env
    depends_on:
      - db
      - redis

  celery-beat:
    build:
      context: .
    command: celery -A cost_accounting_manager beat -l info
    volumes:
      - .:/usr/src/cost_accounting_manager
#    env_file: ./.env
    depends_on:
        - db
        - redis
volumes:
  data: